import { type Moh740Data } from "../../types";
export enum Moh740Rgisters {
    DailyRegister = 'MOH 722 Daily Register',
    PermanentRegister = 'MOH 270 Permanent Register'
}

type RegisterKeys = keyof Moh740Data;

const Moh740DIncatorRegisterMap: Record <RegisterKeys, string> = {
 location_id: '',
  facility: '',
  mfl_code: '',
  county: '',
  sub_county: '',
  reportingMonth: '',
  cumulative_diabetes_patients_in_care: Moh740Rgisters.PermanentRegister,
  newly_diagnosed_diabetes: Moh740Rgisters.DailyRegister,
  total_type_1_diabetes: Moh740Rgisters.DailyRegister,
  total_type_2_diabetes: Moh740Rgisters.DailyRegister,
  cumulative_htn_patient: Moh740Rgisters.PermanentRegister,
  covered_by_shif: Moh740Rgisters.PermanentRegister,
  screened_for_tb_this_month: Moh740Rgisters.DailyRegister,
  screened_postive_for_tb_this_month: Moh740Rgisters.DailyRegister,
  screened_for_diabetic_foot_this_month: Moh740Rgisters.DailyRegister,
  has_diabetic_foot: Moh740Rgisters.DailyRegister,
  type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  revisit_to_clinic_known_dm: Moh740Rgisters.DailyRegister,
  amputation_due_to_diabetic_foot: Moh740Rgisters.DailyRegister,
  stroke_diagnosis: Moh740Rgisters.DailyRegister,
  ischemic_heart_disease_diagnosis: Moh740Rgisters.DailyRegister,
  heart_failure_diagnosis: Moh740Rgisters.DailyRegister,
  has_neuropathies: Moh740Rgisters.DailyRegister,
  newly_diagnosed_htn_this_month: Moh740Rgisters.DailyRegister,
  revisit_known_htn: Moh740Rgisters.DailyRegister,
  is_co_morbid: Moh740Rgisters.PermanentRegister,
  revisit_known_co_morbid: Moh740Rgisters.DailyRegister,
  newly_diagnosed_co_morbid_this_month: Moh740Rgisters.DailyRegister,
  on_insulin_this_month: Moh740Rgisters.DailyRegister,
  on_ogla_meds_this_month: Moh740Rgisters.DailyRegister,
  on_both_insulin_and_ogla_meds_this_month: Moh740Rgisters.DailyRegister,
  dc__age_range__0_to_5__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__age_range__6_to_9__type_1_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__age_range__10_to_19__type_1_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__age_range__20_to_35__type_1_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__age_range__36_and_above__type_1_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__age_range__0_to_18__type_2_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__age_range__19_to_35__type_2_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__age_range__36_to_60__type_2_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__age_range__61_and_above__type_2_diabetes_mellitus:Moh740Rgisters.DailyRegister,
  dc__gender__M__cumulative_diabetes_patients_in_care: Moh740Rgisters.PermanentRegister,
  dc__gender__F__cumulative_diabetes_patients_in_care: Moh740Rgisters.PermanentRegister,
  dc__gender__M__newly_diagnosed_diabetes: Moh740Rgisters.DailyRegister,
  dc__gender__F__newly_diagnosed_diabetes: Moh740Rgisters.DailyRegister,
  dc__gender__M__revisit_to_clinic_known_dm: Moh740Rgisters.DailyRegister,
  dc__gender__F__revisit_to_clinic_known_dm: Moh740Rgisters.DailyRegister,
  dc__gender__M__total_type_1_diabetes: Moh740Rgisters.DailyRegister,
  dc__gender__F__total_type_1_diabetes: Moh740Rgisters.DailyRegister,
  dc__gender__M__total_type_2_diabetes: Moh740Rgisters.DailyRegister,
  dc__gender__F__total_type_2_diabetes: Moh740Rgisters.DailyRegister,
  dc__gender__M__cumulative_htn_patient: Moh740Rgisters.PermanentRegister,
  dc__gender__F__cumulative_htn_patient: Moh740Rgisters.PermanentRegister,
  dc__gender__F__newly_diagnosed_htn_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__newly_diagnosed_htn_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__revisit_known_htn: Moh740Rgisters.DailyRegister,
  dc__gender__F__revisit_known_htn: Moh740Rgisters.DailyRegister,
  dc__gender__M__is_co_morbid: Moh740Rgisters.DailyRegister,
  dc__gender__F__is_co_morbid: Moh740Rgisters.DailyRegister,
  dc__gender__F__revisit_known_co_morbid: Moh740Rgisters.DailyRegister,
  dc__gender__M__revisit_known_co_morbid: Moh740Rgisters.DailyRegister,
  dc__gender__M__newly_diagnosed_co_morbid_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__newly_diagnosed_co_morbid_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__10_to_19__diabetes_mellitus_type__diabetes_mellitus_type_1__total: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__0_to_9__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__0_to_9__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__10_to_19__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__10_to_19__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__20_to_35__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__20_to_35__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__36_to_60__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__36_to_60__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__61_and_above__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__61_and_above__has_htn: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__10_to_19__total: Moh740Rgisters.DailyRegister,
  dc__gender__M__screened_for_tb_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__screened_for_tb_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__screened_postive_for_tb_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__screened_postive_for_tb_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__covered_by_shif: Moh740Rgisters.PermanentRegister,
  dc__gender__F__covered_by_shif: Moh740Rgisters.PermanentRegister,
  dc__gender__M__screened_for_diabetic_foot_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__screened_for_diabetic_foot_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__has_diabetic_foot: Moh740Rgisters.DailyRegister,
  dc__gender__F__has_diabetic_foot: Moh740Rgisters.DailyRegister,
  dc__gender__M__amputation_due_to_diabetic_foot: Moh740Rgisters.DailyRegister,
  dc__gender__F__amputation_due_to_diabetic_foot: Moh740Rgisters.DailyRegister,
  dc__gender__M__stroke_diagnosis: Moh740Rgisters.DailyRegister,
  dc__gender__F__stroke_diagnosis: Moh740Rgisters.DailyRegister,
  dc__gender__M__ischemic_heart_disease_diagnosis: Moh740Rgisters.DailyRegister,
  dc__gender__F__ischemic_heart_disease_diagnosis: Moh740Rgisters.DailyRegister,
  dc__gender__M__heart_failure_diagnosis: Moh740Rgisters.DailyRegister,
  dc__gender__F__heart_failure_diagnosis: Moh740Rgisters.DailyRegister,
  dc__gender__M__has_neuropathies: Moh740Rgisters.DailyRegister,
  dc__gender__F__has_neuropathies: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__0_to_5__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__0_to_5__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__6_to_9__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__6_to_9__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__10_to_19__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__10_to_19__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__20_to_35__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__20_to_35__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__36_and_above__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__36_and_above__type_1_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__0_to_18__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__0_to_18__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__19_to_35__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__19_to_35__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__36_to_60__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__36_to_60__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__age_range__61_and_above__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__F__age_range__61_and_above__type_2_diabetes_mellitus: Moh740Rgisters.DailyRegister,
  dc__gender__M__on_insulin_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__on_insulin_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__on_ogla_meds_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__on_ogla_meds_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__on_both_insulin_and_ogla_meds_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__on_both_insulin_and_ogla_meds_this_month: Moh740Rgisters.DailyRegister,
  dc__age_range__0_to_9__has_htn: Moh740Rgisters.DailyRegister,
  dc__age_range__10_to_19__has_htn: Moh740Rgisters.DailyRegister,
  dc__age_range__20_to_35__has_htn: Moh740Rgisters.DailyRegister,
  dc__age_range__36_to_60__has_htn: Moh740Rgisters.DailyRegister,
  dc__age_range__61_and_above__has_htn: Moh740Rgisters.DailyRegister,
  done_hba1c_this_month:Moh740Rgisters.DailyRegister,
  dc__gender__M__done_hba1c_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__done_hba1c_this_month: Moh740Rgisters.DailyRegister,
  hba1c_less_than_7_percent_this_month:Moh740Rgisters.DailyRegister,
  dc__gender__M__hba1c_less_than_7_percent_this_month:Moh740Rgisters.DailyRegister,
  dc__gender__F__hba1c_less_than_7_percent_this_month:Moh740Rgisters.DailyRegister,
  dc__gender__M__on_exercise_and_diet:Moh740Rgisters.DailyRegister,
  dc__gender__F__on_exercise_and_diet:Moh740Rgisters.DailyRegister,
  on_exercise_and_diet:Moh740Rgisters.DailyRegister,
  on_antihypertensives_this_month:Moh740Rgisters.DailyRegister,
  high_bp:Moh740Rgisters.DailyRegister,
  dc__gender__M__on_antihypertensives_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__F__on_antihypertensives_this_month: Moh740Rgisters.DailyRegister,
  dc__gender__M__high_bp:Moh740Rgisters.DailyRegister,
  dc__gender__F__high_bp:Moh740Rgisters.DailyRegister,
};

export function getRegisterByIndicator(indicator: keyof Moh740Data){
    if(Moh740DIncatorRegisterMap[indicator]){
         return Moh740DIncatorRegisterMap[indicator];
    }else{
        return Moh740Rgisters.DailyRegister
    }
}