export const moh412Columns = [
  'serial_no',
  'visit_date',
  'visit_type',
  'client_no',
  'full_names',
  'phone_number',
  'age',
  'location_residence',
  'treatment_supporter_phone_number',

  'via_villi',
  'pap_smear',
  'hpv',
  'cryotherapy',
  'thermocoagulation',
  'leep',

  'cbe',
  'ultrasound',
  'mammogram',
  'colonoscopy',
  'fobt',
  'hiv_status',

  'referral_from',
  'referral_to',
  'follow_up_date',
  'remarks',
];
